export const LOAD_MOVIES = "LOAD_MOVIES";
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIE_GENRES = "LOAD_MOVIES_GENRES";
export const LOAD_MOVIES_GENRES_SUCCESS = 'LOAD_MOVIES_GENRES_SUCCESS';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const USER_SELECT_BY_GENRE = 'USER_SELECT_BY_GENRE'
export const USER_SELECT_BY_RATING = 'USER_SELECT_BY_RATING'